version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"                        
    volumes:
      - /temp/mysql_data:/var/lib/mysql    
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql                      
      PMA_PORT: 3306
    ports:
      - "8080:80"                          
    depends_on:
      - mysql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge                         
